"""
Django settings for cca_service project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import environ


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# Read in .env file
ENV = environ.Env()
environ.Env.read_env()

# Application configuration
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# https://docs.djangoproject.com/en/3.0/ref/settings/
DEBUG = ENV('DEBUG', cast=bool, default=False)
ALLOWED_HOSTS = ENV('ALLOWED_HOSTS').split(',')
CSRF_COOKIE_SECURE = not DEBUG
SECRET_KEY = ENV('SECRET_KEY')
SESSION_COOKIE_SECURE = not DEBUG

# https://docs.djangoproject.com/en/3.0/ref/middleware/#django.middleware.security.SecurityMiddleware
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_HSTS_SECONDS = 0 if DEBUG else ENV('SECURE_HSTS_SECONDS', cast=int, default=60)
SECURE_REFERRER_POLICY = 'strict-origin'
SECURE_SSL_REDIRECT = not DEBUG

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'cca_service.cca_registry',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cca_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cca_service.wsgi.application'

# Rest Framework settings
# https://www.django-rest-framework.org/api-guide/settings/
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ]
}


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': ENV.db('DATABASE_URL')
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

if DEBUG:
    print(f'DEBUG: {DEBUG}')
    print(f'ALLOWED_HOSTS: {ALLOWED_HOSTS}')
    print(f'CSRF_COOKIE_SECURE: {CSRF_COOKIE_SECURE}')
    print(f'SECRET_KEY: {SECRET_KEY}')
    print(f'SESSION_COOKIE_SECURE: {SESSION_COOKIE_SECURE}')
    print(f'SECURE_HSTS_INCLUDE_SUBDOMAINS: {SECURE_HSTS_INCLUDE_SUBDOMAINS}')
    print(f'SECURE_HSTS_PRELOAD: {SECURE_HSTS_PRELOAD}')
    print(f'SECURE_HSTS_SECONDS: {SECURE_HSTS_SECONDS}')
    print(f'SECURE_REFERRER_POLICY: {SECURE_REFERRER_POLICY}')
    print(f'SECURE_SSL_REDIRECT: {SECURE_SSL_REDIRECT}')
