# Generated by Django 3.0.1 on 2019-12-30 19:24

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founding_date', models.DateField(blank=True, default=datetime.date.today)),
                ('school_name', models.CharField(max_length=100)),
                ('school_abbr', models.CharField(max_length=8)),
                ('region', models.CharField(choices=[('EAST', 'East'), ('WEST', 'West')], max_length=10)),
                ('province', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Alberta', 'Alberta'), ('American Samoa', 'American Samoa'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('British Columbia', 'British Columbia'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('District of Columbia', 'District of Columbia'), ('Federated States of Micronesia', 'Federated States of Micronesia'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Guam', 'Guam'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Manitoba', 'Manitoba'), ('Marshall Islands', 'Marshall Islands'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Brunswick', 'New Brunswick'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('Newfoundland and Labrador', 'Newfoundland and Labrador'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Northwest Territories', 'Northwest Territories'), ('Nova Scotia', 'Nova Scotia'), ('Nunavut', 'Nunavut'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Ontario', 'Ontario'), ('Oregon', 'Oregon'), ('Palau', 'Palau'), ('Pennsylvania', 'Pennsylvania'), ('Prince Edward Island', 'Prince Edward Island'), ('Puerto Rico', 'Puerto Rico'), ('Quebec', 'Quebec'), ('Rhode Island', 'Rhode Island'), ('Saskatchewan', 'Saskatchewan'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virgin Islands', 'Virgin Islands'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming'), ('Yukon', 'Yukon')], max_length=100)),
                ('color_primary', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Invalid HEX color code', regex='^#[0-9A-F]{6}$')])),
                ('color_secondary', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Invalid HEX color code', regex='^#[0-9A-F]{6}$')])),
                ('color_primary_alternate', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Invalid HEX color code', regex='^#[0-9A-F]{6}$')])),
                ('color_secondary_alternate', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Invalid HEX color code', regex='^#[0-9A-F]{6}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('major', models.CharField(blank=True, default='', max_length=100)),
                ('registration_date', models.DateField(default=datetime.date.today)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cca_registry.School')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cca_registry.Student'),
        ),
    ]
