# Generated by Django 3.0.1 on 2020-01-02 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cca_registry', '0001_create_student_and_school_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
